#ifndef __RT_AI_GENDER_MODEL_H
#define __RT_AI_GENDER_MODEL_H

#include <gender.h>
#include <gender_data.h>

/* model info ... */

// model name
#define RT_AI_GENDER_MODEL_NAME			"gender"
#define RT_AI_GENDER_WORK_BUFFER_BYTES		AI_GENDER_DATA_ACTIVATIONS_SIZE
#define RT_AI_GENDER_DATA_WEIGHTS_SIZE		AI_GENDER_DATA_WEIGHTS_SIZE

#define RT_AI_GENDER_BUFFER_ALIGNMENT		AI_GENDER_ACTIVATIONS_ALIGNMENT

#define RT_AI_GENDER_IN_NUM				AI_GENDER_IN_NUM
#define RT_AI_GENDER_IN_1_SIZE				AI_GENDER_IN_1_SIZE
#define RT_AI_GENDER_IN_1_SIZE_BYTES		AI_GENDER_IN_1_SIZE_BYTES
#define RT_AI_GENDER_IN_TOTAL_SIZE_BYTES	(AI_GENDER_IN_1_SIZE_BYTES)
#define RT_AI_GENDER_IN_SIZE_BYTES			{AI_GENDER_IN_1_SIZE_BYTES}


#define RT_AI_GENDER_OUT_NUM				AI_GENDER_OUT_NUM
#define RT_AI_GENDER_OUT_1_SIZE			AI_GENDER_OUT_1_SIZE
#define RT_AI_GENDER_OUT_1_SIZE_BYTES		AI_GENDER_OUT_1_SIZE_BYTES
#define RT_AI_GENDER_OUT_TOTAL_SIZE_BYTES	(AI_GENDER_OUT_1_SIZE_BYTES)
#define RT_AI_GENDER_OUT_SIZE_BYTES		{AI_GENDER_OUT_1_SIZE_BYTES}


#define RT_AI_GENDER_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
